### ISSUE TITLE
Fails to compile on Linux and MacOS

### ISSUE THREAD

**Issue by daniel071** [hadal1337/ASCII-Doughnut#1]
I'm on Manjaro Linux, kernel `5.6.19-2-MANJARO`

I've tried compiling with gcc, g++, clang and clang++ however, it fails to compile and results in the same error.
This is probably because you included two windows-only headers.
```c++
#include <process.h>

#include <windows.h>
```

Here is the error I get:
```fish
ASCII Doughnut.cpp:2:10: fatal error: process.h: No such file or directory
    2 | #include <process.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by bobabooth** [comment]
I have just removed `#include <process.h>` as it's obsolete.
Unfortunately for the time being, `#include <windows.h>` is needed for the program to run.
