### ISSUE TITLE
the results are printed seperately.

### ISSUE THREAD

**Issue by tgkei** [hadal1337/ASCII-Doughnut#2]
![image](https://user-images.githubusercontent.com/37530453/91253845-c9371980-e79b-11ea-81b2-8fc468d7f91c.png)

As shown above, ```exe``` file print out each pixel of images separately.

**Comment by bobabooth** [comment]
This is working as intended. In order for the program to draw a new doughnut image, it will need to replace the old one, and therefore, there will be a lot of separated images. However, the separated images should be replaced fast enough that it will look like a smooth animation.

**Comment by tgkei** [comment]
> This is working as intended. In order for the program to draw a new doughnut image, it will need to replace the old one, and therefore, there will be a lot of separated images. However, the separated images should be replaced fast enough that it will look like a smooth animation.

Thanks for replying, it is fast enough and I understand your intent, but in my computer, it is slow that it doesn't seem like an animation. How can I fix it?

**Comment by bobabooth** [comment]
Unfortunately, I am unable to identify the problem as it works fine on my computer and my friend's.
We are both on the latest Windows 10 and Visual Studio Community if that helps. My best advice would be to try on another computer to see if there is any difference.
